[project]
name = "pgpe"
version = "1.1.0"
description = "A modern, array API standard implementation of PGPE."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "Davide Tenedini", email = "davide.tenedini@polimi.it" },
]
dependencies = [
    "array-api-compat>=1.13.0",
    "numpy>=2.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pgpe"]

[dependency-groups]
dev = [
    "array-api-strict>=2.4.1",
    "jax>=0.9.0.1",
    "jaxlib>=0.9.0.1",
    "pyrefly>=0.46.0",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "torch>=2.10.0",
    "types-array-api>=1.1.4",
]
